services:
  front:
    build: ./Frontend_react
    ports:
      - 80:80
    container_name: front

  db:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: neighborhood_app_production
      POSTGRES_USER: neighborhood_app
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  backend:
    build: ./ruby
    container_name: rails
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: localhost
      DB_NAME: neighborhood_app_production
      DB_USERNAME: neighborhood_app
      # DB_PASSWORD: root
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: {}
networks:
  default:
    name: myapp_default