services:
  - type: web
    name: frontend
    env: docker
    plan: free  # Adjust the plan as necessary
    dockerfilePath: ./Frontend_react/Dockerfile
    buildCommand: ""  # If you have any build commands, add them here
    startCommand: ""  # If you have any start commands, add them here
    envVars: []
    autoDeploy: true
    ports:
      - port: 80

  # - type: db
  #   name: postgres
  #   plan: standard  # Choose the appropriate plan
  #   properties:
  #     engine: postgres
  #     version: 13  # Adjust the version if needed
  #     databases:
  #       - neighborhood_app_production
  #     user: neighborhood_app
  #     password: ''  # Use Render secrets for passwords and other sensitive information
  #   disk:
  #     name: data
  #     sizeGB: 10  # Adjust the size as necessary

  - type: web
    name: backend
    env: docker
    plan: free  # Adjust the plan as necessary
    dockerfilePath: ./ruby/Dockerfile
    buildCommand: "bundle install"  # Add your build command here
    startCommand: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    envVars:
      - key: DB_HOST
        value: postgres
      - key: DB_NAME
        value: neighborhood_app_production
      - key: DB_USERNAME
        value: neighborhood_app
      # - key: DB_PASSWORD
      #   value: root  # Use Render secrets for passwords and other sensitive information
    autoDeploy: true
    ports:
      - port: 3000
    dependsOn:
      - postgres

databases:
  - name: postgres
    engine: postgres
    version: 13
    settings:
      defaultDatabase: neighborhood_app_production
      user: neighborhood_app
      # password: root  # Use Render secrets for passwords and other sensitive information
    disk:
      size: 10Gi  # Adjust the size as necessary
